## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('spain-routing', ['node'])
    module.source = [
	'spain-routing.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'spain-routing'
    headers.source = [
	'spain-routing.h',
        ]

